### PR TITLE
Update project to RN 0.63.1, new Xcode & Android executors

### PR DESCRIPTION
**Pull request by ryanpedersen42**
Big changes for RN >= 0.60, so updated this to run with CocoaPods and to be able to build green out of the box.
Updated to more current executors.

### CODE REVIEW

**Review by gmemstr — APPROVED** [review]
Given my lack of familiarity with React Native, and the heft of this PR, I've done my best effort review of this.

**Comment by ryanpedersen42** [comment]
Screenshots of iOS (iPhone 11) and Android (Pixel 2)
iOS

Android

**Comment by ryanpedersen42** [comment]
Passing build: https://app.circleci.com/pipelines/github/AwesomeCICD/circleci-demo-react-native/33/workflows/e5b2bba1-9b7a-403e-987a-72099f48c4b9

**Comment by ryanpedersen42** [comment]
@appplemac per our chat, this has been updated to 
1. include comment to passing link
2. add note in config about cocoapods 
3. include comment w/ local simulators

let me know if I missed anything!

**Comment by appplemac** [comment]
Thanks for bearing with my comments @ryanpedersen42 - let’s go ahead and merge this and we can iterate further if needed. Thanks for your work!

**Review by appplemac — APPROVED** [review]

**Comment by appplemac** [comment]
Merging because Ryan doesn’t have the right permissions yet for some reason.

**Pull request merged**
